import requests
import json
import logging

logger = logging.getLogger(__name__)

OLLAMA_API_URL = "http://localhost:11434/api/generate"
# Default to llama3, but could be adjusted based on user's local models
DEFAULT_MODEL = "llama3"

def generate_security_report(permissions, risk_analysis, model=DEFAULT_MODEL):
    """
    Calls the local Ollama API to generate a security report based on the APK's permissions.
    """
    
    if not permissions:
        return "No permissions found to analyze."

    prompt = f"""
    You are a mobile security expert. I will provide you with a list of Android permissions extracted from an APK file, 
    along with a basic rule-based risk score. Please generate a concise security report.
    
    Rule-based Risk Level: {risk_analysis.get('level')}
    Rule-based Risk Score: {risk_analysis.get('score')}/100
    
    Permissions:
    {', '.join(permissions)}
    
    Your report MUST include:
    1. Risk Explanation: A brief summary of why these permissions might be requested.
    2. Possible Malicious Behavior: How these permissions could be abused if the app is malicious.
    3. User Recommendation: Clear, actionable advice for a user considering installing this app.
    
    Format the output cleanly in Markdown. Keep it concise.
    """
    
    payload = {
        "model": model,
        "prompt": prompt,
        "stream": False
    }
    
    try:
        response = requests.post(OLLAMA_API_URL, json=payload, timeout=60)
        response.raise_for_status()
        
        result = response.json()
        return result.get("response", "No response generated by the model.")
        
    except requests.exceptions.ConnectionError:
        logger.error("Could not connect to Ollama.")
        return "Error: Could not connect to local Ollama instance. Is Ollama running on http://localhost:11434 ?"
    except requests.exceptions.Timeout:
        logger.error("Ollama request timed out.")
        return "Error: The AI model took too long to respond. The request timed out."
    except Exception as e:
        logger.error(f"Error communicating with Ollama: {str(e)}")
        return f"Error communicating with AI model: {str(e)}"
